[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "easyprotolib"
version = "0.1.1"
authors = [
    { name = "baiYunMieAwa", email = "baiyunmie@163.com" },
]
description = "A Minecraft protocol library written in Python."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT License" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mutf8>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/baiYunMieAwa/EasyProtoLib"
"Bug Tracker" = "https://github.com/baiYunMieAwa/EasyProtoLib/issues"

[tool.setuptools.packages.find]
where = ["src"]

# [tool.setuptools]
# ext-modules = [
#     {name = "pack", sources = ["src/easyprotolib/_pack.pyx"]},
# ]
